default:
  image:
    name: dolfinx/dolfinx:v0.7.2
    pull_policy: always # Not possible to use if-not-present on public runner.

stages:
  - build-lint-and-test
  - pages

build-lint-and-test:
  stage: build-lint-and-test
  script:
    - export DEB_PYTHON_INSTALL_LAYOUT='deb_system'
    - python3 -m pip install '.[ci]'

    # lint and check formatting
    - ruff check .
    - ruff format --check .

    # Run unit tests
    - python3 -m pytest tests/
    - mpirun -n 2 python3 -m pytest tests/

    # Run demos
    - python3 demo/demo_motivation.py
    - mpirun -n 2 python3 demo/demo_motivation.py
    - python3 demo/mixed-poisson/demo_mixed-poisson.py
    - mpirun -n 2 python3 demo/mixed-poisson/demo_mixed-poisson.py
    - python3 demo/navier-stokes-pcd/demo_navier-stokes-pcd.py
    - mpirun -n 2 python3 demo/navier-stokes-pcd/demo_navier-stokes-pcd.py

    # Run examples
    - python3 -m pytest examples/rayleigh-benard-convection/
    - mpirun -n 2 python3 -m pytest examples/rayleigh-benard-convection/

pages:
  stage: pages
  script:
    - export DEB_PYTHON_INSTALL_LAYOUT='deb_system'
    - python3 -m pip install '.[docs]'
    - cd doc && make -e SPHINXOPTS="-t html" html && cd ../
    - cp -r doc/build/html public
  artifacts:
    public: true
    paths:
      - public
  only:
    - main
