FROM dolfinx/dolfinx:v0.5.1-r1 as dev
LABEL description="fenicsx-pctools development image with all FEniCS components installed"

# https://github.com/pypa/setuptools/issues/3269#issuecomment-1254507377
ENV DEB_PYTHON_INSTALL_LAYOUT=deb_system
